### ISSUE TITLE
[Enhancement] Remember TagLEET window position

### ISSUE THREAD

**Issue by pidgeon777** [vinsworldcom/nppTagLEET#1]
Each time the tag window is opened, its position and size is reset.
I suggest adding an option so that this behavior can be controlled.

**Comment by vinsworldcom** [comment]
The original author provides source [here](https://github.com/gstavi/npp/tree/master/tagleet),  Perhaps raise the issue there?  I'll be happy to pull in changes.

I cloned the original repo and enhanced it since the original code didn't have the functionality I wanted.  I'm not familiar enough with the architecture to understand where / how to add tracking of window size and position.
