### ISSUE TITLE
[Enhancement] Remember selected match when reopening TagLEET window

### ISSUE THREAD

**Issue by pidgeon777** [vinsworldcom/nppTagLEET#2]
Let's consider this case:

I select a Word.
I open TagLEET window.
I select one of the results.
I press enter.
I select the same word.
I re-open the TagLEET window.

then the first highlighted result of the tag search results window is still the first row.
It would be nice to maintain the previous selected item instead, so that for example by pressing the down arrow key then the next search result is selected when re-opening the tag window.

**Comment by vinsworldcom** [comment]
The original author provides source [here](https://github.com/gstavi/npp/tree/master/tagleet),  Perhaps raise the issue there?  I'll be happy to pull in changes.

I cloned the original repo and enhanced it since the original code didn't have the functionality I wanted.  I'm not familiar enough with the architecture to understand where / how to add a tracking list for previously selected words.
